#' Scales processes by grouping
#'
#' For use in compiler
#'
#' @param tblprocess table of processes to be scaled as generated by compiler
#' @param tblgroups table of grouping process for scaling
#' @param scalecol column name to scale processes by type (e.g., transition,
#' migration, interaction)
#' @return named vector with immediate names
scaleprocesstblbygroups <- function(tblprocess, tblgroups, scalecol) {
  tblprocess <- tblprocess |> dplyr::mutate(scalerate = "")
  tblprocess_hasname <- TRUE %in% !is.na(tblprocess$processname)
  tblprocess_hasgroup <- TRUE %in% !is.na(tblprocess$processgroup)

  # loop through state groups
  for (loopidx in seq_len(nrow(tblgroups))) {
    currtblgroups <- tblgroups[loopidx, ]
    prelogic <- tblprocess[[currtblgroups$grouptype]] == currtblgroups$groupname
    currlogic <- !is.na(prelogic) & prelogic

    # scale by label
    if (currtblgroups[[scalecol]] != "") {
      tblprocess$scalerate[currlogic] <-
        paste0(
          as.character(currtblgroups[[scalecol]]),
          tblprocess$scalerate[currlogic]
        )
    }
    # scale by group
    if (tblprocess_hasgroup) {
      if (FALSE %in% sapply(currtblgroups$scaleprocessbygroup, function(x) {
        x == ""
      })) {
        tbl2hit <-
          tibble::tibble(
            processgroup =
              names(currtblgroups$scaleprocessbygroup[[1]]), # nolint: indentation_linter, line_length_linter.
            addscalerate = currtblgroups$scaleprocessbygroup[[1]]
          )

        temptblprocess <-
          dplyr::left_join(tblprocess, tbl2hit, by = "processgroup") |>
          tidyr::replace_na(list(addscalerate = list("")))

        currlogic2 <- (currlogic) &
          (!is.na(temptblprocess$addscalerate)) &
          (temptblprocess$addscalerate != "")

        tblprocess$scalerate[currlogic2] <-
          paste0(
            as.character(temptblprocess$addscalerate[currlogic2]),
            tblprocess$scalerate[currlogic2]
          )
      }
    }

    # scale by name
    if (tblprocess_hasname) {
      if (FALSE %in% sapply(currtblgroups$scaleprocessbyname, function(x) {
        x == ""
      })) {
        currnamescales <- mixedunlist(currtblgroups$scaleprocessbyname[[1]])
        tbl2hit <-
          tibble::tibble(
            processname = names(currnamescales),
            addscalerate = currnamescales
          )

        temptblprocess <-
          dplyr::left_join(tblprocess, tbl2hit, by = "processname")
        currlogic2 <- (currlogic) &
          (!is.na(temptblprocess$addscalerate)) &
          (temptblprocess$addscalerate != "")

        tblprocess$scalerate[currlogic2] <-
          paste0(
            as.character(temptblprocess$addscalerate[currlogic2]),
            tblprocess$scalerate[currlogic2]
          )
      }
    }
  }
  tblprocess <- tblprocess |>
    dplyr::mutate(rate = paste0(.data$scalerate, .data$rate)) |>
    dplyr::select(-"scalerate")

  return(tblprocess)
}
