#' Scales processes by space
#'
#' For use in compiler
#'
#' @param tblprocess table of processes to be scaled as generated by compiler
#' @param tblspace table of how processes scale between metapopulations
#' @param scalecol column name to scale processes by type (e.g., scaletranstion)
#' @return named vector with immediate names
scaleprocesstblbyspace <- function(tblprocess, tblspace, scalecol) {
  tblprocess_hasname <- TRUE %in% !is.na(tblprocess$processname)
  tblprocess_hasgroup <- TRUE %in% !is.na(tblprocess$processgroup)

  # global
  tblprocess <- dplyr::left_join(tblprocess,
    tblspace[, c("metapopulation", scalecol)],
    by = "metapopulation"
  ) |>
    dplyr::rename(scalerate = .data[[scalecol]])

  # loop through state groups
  for (loopidx in seq_len(nrow(tblspace))) {
    currtblspace <- tblspace[loopidx, ]
    currlogic <- tblprocess[["metapopulation"]] ==
      currtblspace[["metapopulation"]]

    # scale by group
    if (tblprocess_hasgroup) {
      if (FALSE %in% sapply(currtblspace$scaleprocessbygroup, function(x) {
        x == ""
      })) {
        tbl2hit <- tibble::tibble(
          processgroup =
            names(currtblspace$scaleprocessbygroup[[1]]),
          addscalerate =
            currtblspace$scaleprocessbygroup[[1]]
        )

        temptblprocess <- dplyr::left_join(tblprocess,
          tbl2hit,
          by = "processgroup"
        ) |>
          tidyr::replace_na(list(addscalerate = list("")))

        currlogic2 <- (currlogic) &
          (!is.na(temptblprocess$addscalerate)) &
          (temptblprocess$addscalerate != "")

        tblprocess$scalerate[currlogic2] <-
          paste0(
            as.character(temptblprocess$addscalerate[currlogic2]),
            tblprocess$scalerate[currlogic2]
          )
      }
    }

    # scale by name
    if (tblprocess_hasname) {
      if (FALSE %in% sapply(currtblspace$scaleprocessbyname, function(x) {
        x == ""
      })) {
        currnamescales <- mixedunlist(currtblspace$scaleprocessbyname[[1]])
        tbl2hit <- tibble::tibble(
          processname = names(currnamescales),
          addscalerate = currnamescales
        )

        temptblprocess <- dplyr::left_join(tblprocess,
          tbl2hit,
          by = "processname"
        )
        currlogic2 <- (currlogic) &
          (!is.na(temptblprocess$addscalerate)) &
          (temptblprocess$addscalerate != "")

        tblprocess$scalerate[currlogic2] <-
          paste0(
            as.character(temptblprocess$addscalerate[currlogic2]),
            tblprocess$scalerate[currlogic2]
          )
      }
    }
  }
  tblprocess <- tblprocess |>
    dplyr::mutate(rate = paste0(.data$scalerate, .data$rate)) |>
    dplyr::select(-"scalerate")

  return(tblprocess)
}
